#include <imgui-core/inc/imgui-modules.h>

#define ENUM(e, v) value(#v, e##_##v)

void init_enums(py::module& m)
{
    py::enum_<ImGuiWindowFlags_>(m, "WindowFlags")
        .ENUM(ImGuiWindowFlags, None)
        .ENUM(ImGuiWindowFlags, NoTitleBar)
        .ENUM(ImGuiWindowFlags, NoResize)
        .ENUM(ImGuiWindowFlags, NoMove)
        .ENUM(ImGuiWindowFlags, NoScrollbar)
        .ENUM(ImGuiWindowFlags, NoScrollWithMouse)
        .ENUM(ImGuiWindowFlags, NoCollapse)
        .ENUM(ImGuiWindowFlags, AlwaysAutoResize)
        .ENUM(ImGuiWindowFlags, NoBackground)
        .ENUM(ImGuiWindowFlags, NoSavedSettings)
        .ENUM(ImGuiWindowFlags, NoMouseInputs)
        .ENUM(ImGuiWindowFlags, MenuBar)
        .ENUM(ImGuiWindowFlags, HorizontalScrollbar)
        .ENUM(ImGuiWindowFlags, NoFocusOnAppearing)
        .ENUM(ImGuiWindowFlags, NoBringToFrontOnFocus)
        .ENUM(ImGuiWindowFlags, AlwaysVerticalScrollbar)
        .ENUM(ImGuiWindowFlags, AlwaysHorizontalScrollbar)
        .ENUM(ImGuiWindowFlags, AlwaysUseWindowPadding)
        .ENUM(ImGuiWindowFlags, NoNavInputs)
        .ENUM(ImGuiWindowFlags, NoNavFocus)
        .ENUM(ImGuiWindowFlags, UnsavedDocument)
        .ENUM(ImGuiWindowFlags, NoNav)
        .ENUM(ImGuiWindowFlags, NoDecoration)
        .ENUM(ImGuiWindowFlags, NoInputs);

    py::enum_<ImGuiInputTextFlags_>(m, "InputTextFlags")
        .ENUM(ImGuiInputTextFlags, None)
        .ENUM(ImGuiInputTextFlags, CharsDecimal)
        .ENUM(ImGuiInputTextFlags, CharsHexadecimal)
        .ENUM(ImGuiInputTextFlags, CharsUppercase)
        .ENUM(ImGuiInputTextFlags, CharsNoBlank)
        .ENUM(ImGuiInputTextFlags, AutoSelectAll)
        .ENUM(ImGuiInputTextFlags, EnterReturnsTrue)
        .ENUM(ImGuiInputTextFlags, CallbackCompletion)
        .ENUM(ImGuiInputTextFlags, CallbackHistory)
        .ENUM(ImGuiInputTextFlags, CallbackAlways)
        .ENUM(ImGuiInputTextFlags, CallbackCharFilter)
        .ENUM(ImGuiInputTextFlags, AllowTabInput)
        .ENUM(ImGuiInputTextFlags, CtrlEnterForNewLine)
        .ENUM(ImGuiInputTextFlags, NoHorizontalScroll)
        .ENUM(ImGuiInputTextFlags, AlwaysOverwrite)
        .ENUM(ImGuiInputTextFlags, ReadOnly)
        .ENUM(ImGuiInputTextFlags, Password)
        .ENUM(ImGuiInputTextFlags, NoUndoRedo)
        .ENUM(ImGuiInputTextFlags, CharsScientific)
        .ENUM(ImGuiInputTextFlags, CallbackResize)
        .ENUM(ImGuiInputTextFlags, CallbackEdit)
        .ENUM(ImGuiInputTextFlags, EscapeClearsAll);

    py::enum_<ImGuiTreeNodeFlags_>(m, "TreeNodeFlags")
        .ENUM(ImGuiTreeNodeFlags, None)
        .ENUM(ImGuiTreeNodeFlags, Selected)
        .ENUM(ImGuiTreeNodeFlags, Framed)
        .ENUM(ImGuiTreeNodeFlags, AllowItemOverlap)
        .ENUM(ImGuiTreeNodeFlags, NoTreePushOnOpen)
        .ENUM(ImGuiTreeNodeFlags, NoAutoOpenOnLog)
        .ENUM(ImGuiTreeNodeFlags, DefaultOpen)
        .ENUM(ImGuiTreeNodeFlags, OpenOnDoubleClick)
        .ENUM(ImGuiTreeNodeFlags, OpenOnArrow)
        .ENUM(ImGuiTreeNodeFlags, Leaf)
        .ENUM(ImGuiTreeNodeFlags, Bullet)
        .ENUM(ImGuiTreeNodeFlags, FramePadding)
        .ENUM(ImGuiTreeNodeFlags, SpanAvailWidth)
        .ENUM(ImGuiTreeNodeFlags, NavLeftJumpsBackHere)
        .ENUM(ImGuiTreeNodeFlags, CollapsingHeader);

    py::enum_<ImGuiPopupFlags_>(m, "PopupFlags")
        .ENUM(ImGuiPopupFlags, None)
        .ENUM(ImGuiPopupFlags, MouseButtonLeft)
        .ENUM(ImGuiPopupFlags, MouseButtonRight)
        .ENUM(ImGuiPopupFlags, MouseButtonMiddle)
        .ENUM(ImGuiPopupFlags, MouseButtonMask_)
        .ENUM(ImGuiPopupFlags, MouseButtonDefault_)
        .ENUM(ImGuiPopupFlags, NoOpenOverExistingPopup)
        .ENUM(ImGuiPopupFlags, NoOpenOverItems)
        .ENUM(ImGuiPopupFlags, AnyPopupId)
        .ENUM(ImGuiPopupFlags, AnyPopupLevel)
        .ENUM(ImGuiPopupFlags, AnyPopup);

    py::enum_<ImGuiSelectableFlags_>(m, "SelectableFlags")
        .ENUM(ImGuiSelectableFlags, None)
        .ENUM(ImGuiSelectableFlags, DontClosePopups)
        .ENUM(ImGuiSelectableFlags, SpanAllColumns)
        .ENUM(ImGuiSelectableFlags, AllowDoubleClick)
        .ENUM(ImGuiSelectableFlags, Disabled)
        .ENUM(ImGuiSelectableFlags, AllowItemOverlap);
}