name: dist

on:
  pull_request:
  push:
    branches:
    - main
    tags:
    - '*'

env:
  FORCE_COLOR: 1

jobs:
  sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: python -m pip install build
      - run: python -m build -s
      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
  wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-13
          - macos-14
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: pypa/cibuildwheel@v2.18.1
        env:
          CIBW_BEFORE_ALL_LINUX: >
            yum install -y
            libXrandr-devel
            libXinerama-devel
            libXcursor-devel
            libXi-devel
            mesa-libGL-devel
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs:
      - sdist
      - wheels
    environment:
      name: pypi
      url: https://pypi.org/p/py-imgui-redux
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true